meta_product_name: "Mon Député"
meta_title: "Mon Député - Découvrez qui est votre élu"
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
